### ISSUE TITLE
Splash screen not being used on apps

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase-iOS-Xcode-template#19]
### Describe the bug

The Xcode project definition includes a launch storyboard; but for some reason, the storyboard is not being used when launching iOS apps

### Steps to reproduce

1. Generate a hello world project
2. Run on iOS

On launch, you get a black screen before the app is shown. The launch screen isn't shown.

### Expected behavior

The "Made with BeeWare" launch screen should be displayed on app startup.

### Environment

- Operating System: iOS 16.4
- Python version: 3.10 (but likely all versions)
- Software versions:
  - Briefcase: 0.3.14
  - Toga: 0.3.1
  - ...

### Logs

```

```

### Additional context

This *did* work in the past; it's likely been broken as a result of an Xcode upgrade at some point.

**Comment by freakboy3742** [comment]
This appears to be dependent on your test device. The iPhone SE 3rd edition simulator *does* show the splash screen; iPhone 14 Pro doesn't.

**Comment by Cheukting** [comment]
According to https://stackoverflow.com/a/65887503 this answer, since iOS 14 images for the launch screen are limited to 25 MB, So reducing the size of the 3x splash image to 2400 x 2400 will solve the issue

**Comment by Cheukting** [comment]
We can redesign the 3 images to be 800, 1600 and 2400
