### ISSUE TITLE
cannot create iOS project

### ISSUE THREAD

**Issue by alexzanderr** [beeware/briefcase-iOS-Xcode-template#4]
hello. briefcase and beeware are great projects. i have special thanks for them. 

i deployed an app for android and right now im trying for iOS, but i cant seem to work out.

what i did until now:
- i've copied this template with cookiecutter. (generated) 
- i've created the python app.
- i've run the python app, works on linux machine.
- i have a pyproject.toml that requires `toga-iOS==0.3.0.dev29`
- i've tried to run `briefcase create ios` and `briefcase create iOS` but i get this error:

```sh
❱  briefcase create iOS

iOS applications require Xcode, which is only available on macOS.
```
which takes me to wonder: do i really need to be on MacOS machine to actually build this project for iOS ?

but wait. i have a `xcode` project file in there.

here is my project tree
```sh
❱  exa --tree --icons --level 3
 .
├──  briefcase.toml
├──  ios_app
│  ├──  app
│  │  ├──  __init__.py
│  │  ├──  __main__.py
│  │  ├──  __pycache__
│  │  ├──  app.py
│  │  └──  README
│  ├──  app_packages
│  │  ├──  nslog.py
│  │  └──  README
│  ├──  en.lproj
│  │  └──  InfoPlist.strings
│  ├──  Images.xcassets
│  │  ├──  AppIcon.appiconset
│  │  └──  Splash.imageset
│  ├──  ios_app-Info.plist
│  ├──  ios_app-Prefix.pch
│  ├──  Launch Screen.storyboard
│  └──  main.m
├──  IOS_APP.xcodeproj
│  └──  project.pbxproj
├──  pyproject.toml
└──  Support
   ├──  BZip2
   │  ├──  Headers
   │  └──  libbzip2.a
   ├──  libFFI
   │  ├──  Headers
   │  └──  libFFI.a
   ├──  OpenSSL
   │  ├──  Headers
   │  └──  libOpenSSL.a
   ├──  Python
   │  ├──  Headers
   │  ├──  libPython.a
   │  └──  Resources
   ├──  README
   ├──  VERSIONS
   └──  XZ
      ├──  Headers
      └──  libxz.a
```
note: under `Support` folder i extracted what was recommended to put in there from this section of readme:

> Download the Python Apple support package for iOS, and extract it into the My Project directory generated by the template. This will give you a My Project/Support directory containing a self contained Python install.
Alternatively, you can download the Python-Apple-support project, and build your own version.

wait i just saw this:

> `You're now ready to open the XCode project file, build and run your project!`

this means that i should open this entire project with XCode editor from MacOS to build and run ?

my machine:
- arch linux (manjaro 21 xfce)
- kernel: `Kernel: 5.10.79-1-MANJARO`

the question: can i build this python project for IOS devices on linux environment?

**Comment by alexzanderr** [comment]
i mean, its pretty straight forward this message: `
iOS applications require Xcode, which is only available on macOS.` and i understand what it means, but isnt there a workaround for this? to not make me install macOS in virtual machine?

**Comment by freakboy3742** [comment]
Unfortunately, the tools needed to build iOS apps are only provided on macOS.
