### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by marco-theraforge** [beeware/briefcase-iOS-Xcode-template#6]
[Download the Python Apple support package for iOS](https://briefcase-support.org/python?platform=iOS&version=3.11)

this link yields a Not Found page:

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by freakboy3742** [comment]
This is because Python3.11 hasn't been released yet. The link will become active when Python3.11 support is published.
